### ISSUE TITLE
Bug on clustering-> plot 3d graph

### ISSUE THREAD

**Issue by SanyHe** [ZJUEarthData/geochemistrypi#49]
(1) System Environment:
+ Systerm version: macOS Catalina version 10.15.7
+ Python version: 3.9.7 

(2) Problem:
When I wanna plot the result in 3 dimensional space, the error occurs.

(3) Log:
```python
-----* Plot 3d Graph *-----
Save figure 'Plot 3d Graph - KMeans' in /Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/images/model_output.
Traceback (most recent call last):
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/main.py", line 233, in <module>
    main()
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/main.py", line 223, in main
    run.activate(X, y)
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/../process/cluster.py", line 29, in activate
    self.clt_workflow.special_components()
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/../model/clustering.py", line 233, in special_components
    self.plot_3d_graph()
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/../model/clustering.py", line 183, in plot_3d_graph
    save_fig(f"Plot 3d Graph - {self.naming}", MODEL_OUTPUT_IMAGE_PATH)
  File "/Users/can/Documents/github/work/geo_ml/geochemistrypy/geochemistrypy/client/../utils/base.py", line 26, in save_fig
    plt.savefig(path, format='png', dpi=300)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    FigureCanvasAgg.draw(self)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.9/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 445, in draw
    sorted(self.collections,
  File "/usr/local/lib/python3.9/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 446, in <lambda>
    key=lambda col: col.do_3d_projection(renderer),
  File "/usr/local/lib/python3.9/site-packages/mpl_toolkits/mplot3d/art3d.py", line 494, in do_3d_projection
    ecs = (_zalpha(self._edgecolor3d, vzs) if self._depthshade else
  File "/usr/local/lib/python3.9/site-packages/mpl_toolkits/mplot3d/art3d.py", line 810, in _zalpha
    rgba = np.broadcast_to(mcolors.to_rgba_array(colors), (len(zs), 4))
  File "<__array_function__ internals>", line 5, in broadcast_to
  File "/usr/local/lib/python3.9/site-packages/numpy/lib/stride_tricks.py", line 180, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/usr/local/lib/python3.9/site-packages/numpy/lib/stride_tricks.py", line 123, in _broadcast_to
    it = np.nditer(
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (0,4) and requested shape (1904,4)
```

(4) Idea:

**Comment by Jinger52035** [comment]
I'm working on it
